// ================================================
// 道北景點資料庫 spots.js
// 旭川／美瑛／富良野／東川
// ================================================

const SPOTS = [

  // ==================== 旭川市區 ====================
  {
    id: 1,
    name: '旭山動物園',
    city: 'asahikawa',
    area: '旭川市區',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '北海道代表景點，冬季企鵝散步限定活動',
  },
  {
    id: 2,
    name: '旭川拉麵村',
    city: 'asahikawa',
    area: '旭川市區',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '雪天超適合，6家名店集中',
  },
  {
    id: 3,
    name: '神居古潭',
    city: 'asahikawa',
    area: '旭川市區',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: false,
    winter: false,
    note: '冬天需注意結冰，夏秋最適合',
  },
  {
    id: 4,
    name: '買物公園',
    city: 'asahikawa',
    area: '旭川市區',
    type: '半室內',
    rain: true,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '市區散步商圈，部分室內',
  },
  {
    id: 5,
    name: '旭川市科學館',
    city: 'asahikawa',
    area: '旭川市區',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '雨雪天最佳備案，親子首選',
  },
  {
    id: 6,
    name: '高砂酒造',
    city: 'asahikawa',
    area: '旭川市區',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: false,
    winter: true,
    note: '日本酒觀光工廠，成人限定',
  },
  {
    id: 7,
    name: '男山酒造資料館',
    city: 'asahikawa',
    area: '旭川市區',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: false,
    winter: true,
    note: '免費試飲，歷史建築',
  },
  {
    id: 8,
    name: '旭橋',
    city: 'asahikawa',
    area: '旭川市區',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: false,
    winter: true,
    note: '旭川代表攝影點，冬季雪景美',
  },
  {
    id: 9,
    name: '常磐公園',
    city: 'asahikawa',
    area: '旭川市區',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: false,
    note: '春夏最漂亮，冬天較冷清',
  },
  {
    id: 10,
    name: '永山美食街',
    city: 'asahikawa',
    area: '旭川市區',
    type: '室內型商圈',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '停車方便，在地居酒屋燒肉聚集',
  },

  // ==================== 旭川在地生活系 ====================
  {
    id: 11,
    name: 'AEON Mall 旭川駅前',
    city: 'asahikawa',
    area: '旭川生活',
    type: '百貨',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '暴雪最強避難所，購物餐飲全包',
  },
  {
    id: 12,
    name: 'Feeeal Asahikawa',
    city: 'asahikawa',
    area: '旭川生活',
    type: '百貨',
    rain: true,
    heavy_snow: false,
    blizzard: false,
    family: false,
    winter: true,
    note: '市區購物，靠近車站',
  },
  {
    id: 13,
    name: 'JR 旭川車站商圈',
    city: 'asahikawa',
    area: '旭川生活',
    type: '車站商圈',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '城市核心，任何天氣都能去',
  },
  {
    id: 14,
    name: '道の駅あさひかわ',
    city: 'asahikawa',
    area: '旭川生活',
    type: '道之驛',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '伴手禮採購，室內空間寬敞',
  },
  {
    id: 15,
    name: '旭川市博物館',
    city: 'asahikawa',
    area: '旭川生活',
    type: '博物館',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: false,
    winter: true,
    note: '愛努文化展示，深度旅遊',
  },
  {
    id: 16,
    name: '三浦綾子記念文學館',
    city: 'asahikawa',
    area: '旭川生活',
    type: '文學館',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: false,
    winter: true,
    note: '安靜系，文學愛好者',
  },
  {
    id: 17,
    name: '旭川冬まつり會場',
    city: 'asahikawa',
    area: '旭川生活',
    type: '季節活動',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '冬季限定，需確認活動日期',
  },

  // ==================== 美瑛 ====================
  {
    id: 18,
    name: '白金青池',
    city: 'biei',
    area: '美瑛',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '冬季夜間點燈特別美，晴天更推薦',
  },
  {
    id: 19,
    name: '白鬚瀑布',
    city: 'biei',
    area: '美瑛',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '青池旁順路必看，冬天有冰柱',
  },
  {
    id: 20,
    name: '四季彩之丘',
    city: 'biei',
    area: '美瑛',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: false,
    note: '夏季花田核心景點',
  },
  {
    id: 21,
    name: '拓真館',
    city: 'biei',
    area: '美瑛',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: false,
    winter: true,
    note: '美瑛攝影展館，室內備案',
  },
  {
    id: 22,
    name: '道の駅びえい「丘のくら」',
    city: 'biei',
    area: '美瑛',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '自駕必停，伴手禮齊全',
  },
  {
    id: 23,
    name: '美瑛選果',
    city: 'biei',
    area: '美瑛',
    type: '美食／伴手禮',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '玉米麵包超人氣，室內購物',
  },
  {
    id: 24,
    name: '肯與瑪麗之木',
    city: 'biei',
    area: '美瑛',
    type: '景點',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: false,
    winter: false,
    note: '開車拍照，晴天效果最佳',
  },
  {
    id: 25,
    name: '七星之木',
    city: 'biei',
    area: '美瑛',
    type: '景點',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: false,
    winter: false,
    note: '香菸包裝成名，經典孤樹',
  },
  {
    id: 26,
    name: '新栄の丘展望公園',
    city: 'biei',
    area: '美瑛',
    type: '展望',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: false,
    winter: false,
    note: '日落景色強，夏秋推薦',
  },
  {
    id: 27,
    name: '拼布之路',
    city: 'biei',
    area: '美瑛',
    type: '自駕景觀',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: false,
    winter: false,
    note: '夏季代表自駕路線',
  },

  // ==================== 富良野 ====================
  {
    id: 28,
    name: 'Farm Tomita',
    city: 'furano',
    area: '富良野',
    type: '花田',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: false,
    note: '薰衣草發祥地，7月最美，冬季部分開放',
  },
  {
    id: 29,
    name: '寧格爾森林',
    city: 'furano',
    area: '富良野',
    type: '半戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '夜間氣氛強，手工藝小屋',
  },
  {
    id: 30,
    name: '富良野起司工房',
    city: 'furano',
    area: '富良野',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '親子體驗首選，全年開放',
  },
  {
    id: 31,
    name: '富良野葡萄酒工廠',
    city: 'furano',
    area: '富良野',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: false,
    winter: true,
    note: '大人系，試飲購物',
  },
  {
    id: 32,
    name: '風のガーデン',
    city: 'furano',
    area: '富良野',
    type: '花園',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: false,
    note: '夏季漂亮，日劇場景',
  },
  {
    id: 33,
    name: '麓郷展望台',
    city: 'furano',
    area: '富良野',
    type: '展望',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: false,
    winter: false,
    note: '北國之戀取景地，晴天限定',
  },
  {
    id: 34,
    name: '森の時計',
    city: 'furano',
    area: '富良野',
    type: '咖啡廳',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: false,
    winter: true,
    note: '日劇咖啡廳，雨雪天氣氛更好',
  },

  // ==================== 東川／近郊 ====================
  {
    id: 35,
    name: '道の駅ひがしかわ「道草館」',
    city: 'higashikawa',
    area: '東川',
    type: '道之驛',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '東川核心，伴手禮齊全',
  },
  {
    id: 36,
    name: '旭岳纜車',
    city: 'higashikawa',
    area: '東川',
    type: '纜車',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '需看天氣，暴風雪停駛，冬季雪景壯觀',
  },
  {
    id: 37,
    name: '天人峽',
    city: 'higashikawa',
    area: '東川',
    type: '峽谷',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: false,
    winter: true,
    note: '秋天最漂亮，冬季溫泉旅館推薦',
  },
  {
    id: 38,
    name: 'キトウシ森林公園',
    city: 'higashikawa',
    area: '東川',
    type: '公園',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: false,
    note: '親子向，夏春適合',
  },
  {
    id: 39,
    name: '東川町文化ギャラリー',
    city: 'higashikawa',
    area: '東川',
    type: '藝術館',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: false,
    winter: true,
    note: '攝影之町美術展，安靜系',
  },

  // ==================== 名寄 ====================
  {
    id: 40,
    name: '名寄冰雪公園',
    city: 'nayoro',
    area: '名寄',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '冬季雪上活動勝地，滑雪橇',
  },
  {
    id: 41,
    name: '名寄市北國博物館',
    city: 'nayoro',
    area: '名寄',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '道北歷史文化，雨雪天備案',
  },
  {
    id: 42,
    name: 'なよろ星空の里',
    city: 'nayoro',
    area: '名寄',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '日本最佳星空觀測地之一，冬季極光機會',
  },
  {
    id: 43,
    name: '名寄市街商店街',
    city: 'nayoro',
    area: '名寄',
    type: '商圈',
    rain: true,
    heavy_snow: true,
    blizzard: false,
    family: true,
    winter: true,
    note: '道北在地購物，暖身補給',
  },
  {
    id: 44,
    name: 'サンピラーパーク',
    city: 'nayoro',
    area: '名寄',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '光柱現象（サンピラー）觀測勝地，冬季晴天限定',
  },

  // ==================== 稚內 ====================
  {
    id: 45,
    name: '宗谷岬',
    city: 'wakkanai',
    area: '稚內',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '日本最北端，打卡必去',
  },
  {
    id: 46,
    name: '稚內公園・開基百年紀念塔',
    city: 'wakkanai',
    area: '稚內',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '展望台可遠眺利尻島，晴天效果最佳',
  },
  {
    id: 47,
    name: '稚內副港市場',
    city: 'wakkanai',
    area: '稚內',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '海鮮市場＋溫泉，雨雪天完美備案',
  },
  {
    id: 48,
    name: '利尻島渡輪碼頭',
    city: 'wakkanai',
    area: '稚內',
    type: '交通',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: false,
    note: '前往利尻島、禮文島的出發點，夏季限定',
  },
  {
    id: 49,
    name: '稚內溫泉童夢',
    city: 'wakkanai',
    area: '稚內',
    type: '室內',
    rain: true,
    heavy_snow: true,
    blizzard: true,
    family: true,
    winter: true,
    note: '寒冷天氣最佳選擇，泡湯暖身',
  },
  {
    id: 50,
    name: 'ノシャップ岬',
    city: 'wakkanai',
    area: '稚內',
    type: '戶外',
    rain: false,
    heavy_snow: false,
    blizzard: false,
    family: true,
    winter: true,
    note: '夕陽絕景，可看利尻富士，晴天限定',
  },
];

// ================================================
// 天氣對應推薦邏輯
// ================================================
function recommendSpots(weatherLevel, options = {}) {
  const { city, family, winter, limit = 5 } = options;

  let filtered = SPOTS.filter(s => {
    // 城市篩選
    if (city && s.city !== city) return false;

    // 親子篩選
    if (family && !s.family) return false;

    // 冬季篩選
    if (winter && !s.winter) return false;

    // 天氣篩選
    if (weatherLevel === 'blizzard')    return s.blizzard;
    if (weatherLevel === 'heavy_snow')  return s.heavy_snow || s.blizzard;
    if (weatherLevel === 'snow')        return s.rain || s.heavy_snow || s.blizzard;
    if (weatherLevel === 'rain')        return s.rain;
    return true; // 晴天、多雲全部推薦
  });

  return filtered.slice(0, limit);
}

module.exports = { SPOTS, recommendSpots };
